# Generated by Django 3.0.4 on 2020-05-15 16:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('control_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('entry_trigger_percent', models.FloatField(help_text='default: 0.5')),
                ('max_risk_percent_per_trade', models.FloatField(help_text='default: 0.5')),
                ('max_investment_per_position', models.FloatField(help_text='default: 300000.0')),
                ('min_investment_per_position', models.FloatField(help_text='default: 1000.0')),
                ('position_stoploss_percent', models.FloatField(help_text='default: 0.5')),
                ('position_target_stoploss', models.FloatField(help_text='default: 0.1')),
                ('position_target_percent', models.FloatField(help_text='default: 1.0')),
                ('user_stoploss_percent', models.FloatField(help_text='default: 5.0')),
                ('user_target_stoploss', models.FloatField(help_text='default: 1.0')),
                ('user_target_percent', models.FloatField(help_text='default: 10.0')),
                ('entry_time_start', models.DateTimeField(help_text='default: 9:15:04')),
                ('entry_time_end', models.DateTimeField(help_text='default: 15:18:00')),
                ('exit_time', models.DateTimeField(help_text='default: 15:19:00')),
                ('trading_side', models.IntegerField(choices=[(1, 'Short Side'), (2, 'Long Side'), (3, "Don't Trade")], default=1)),
                ('order_variety', models.CharField(choices=[('co', 'CO ORDER'), ('regular', 'REGULAR ORDER')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KiteConnectApp',
            fields=[
                ('hstock_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_kite_app', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_token', models.BigIntegerField(unique=True)),
                ('trading_symbol', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100, unique=True)),
                ('mis_margin', models.FloatField()),
                ('co_margin', models.FloatField()),
                ('co_trigger_percent_lower', models.FloatField()),
                ('co_trigger_percent_upper', models.FloatField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ZerodhaAccount',
            fields=[
                ('hstock_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_zerodha', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_time', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(max_length=100)),
                ('public_token', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_shortname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('exchanges', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('products', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('order_types', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('fund_available', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
