# Generated by Django 3.0.4 on 2020-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodhaaccount',
            name='fund_available',
            field=models.FloatField(default=0.0),
        ),
    ]
