# Generated by Django 3.0.4 on 2020-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='commission_percent',
            field=models.FloatField(default=0.06, help_text='default: 0.06'),
            preserve_default=False,
        ),
    ]
