# Generated by Django 3.0.4 on 2020-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='co_margin',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='mis_margin',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
