# Generated by Django 3.0.4 on 2020-05-26 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0002_controls_commission_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerodhaaccount',
            name='access_token_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerodhaaccount',
            name='public_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhaaccount',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
