# Generated by Django 3.0.4 on 2020-04-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0003_auto_20200331_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodhaaccount',
            name='access_token_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
