# Generated by Django 3.0.4 on 2020-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0004_zerodhaaccount_access_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodhaaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
