# Generated by Django 3.0.4 on 2020-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0004_auto_20200526_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='mock_trading_initial_value',
            field=models.FloatField(default=100000.0, help_text='default:100000.0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controls',
            name='trading_side',
            field=models.IntegerField(choices=[(1, 'Short Side'), (2, 'Long Side'), (3, 'Mock Short Side'), (4, 'Mock Long Side'), (5, "Don't Trade")], default=1),
        ),
    ]
