# Generated by Django 3.0.4 on 2020-05-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0005_auto_20200527_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='trading_side',
            field=models.IntegerField(choices=[(1, 'Short Stopprofit'), (2, 'Long Stopprofit'), (3, 'Short Stoploss'), (4, 'Long Stoploss'), (5, 'Mock Short Stopprofit'), (6, 'Mock Long Stopprofit'), (7, 'Mock Short Stoploss'), (8, 'Mock Long Stoploss'), (9, "Don't Trade")], default=1),
        ),
    ]
