# Generated by Django 3.0.4 on 2020-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktradingapp', '0007_auto_20200530_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='trading_side',
            field=models.IntegerField(choices=[(1, 'Short Stopprofit'), (2, 'Long Stopprofit'), (3, 'Short Stoploss'), (4, 'Long Stoploss'), (5, 'Mock Short Stopprofit'), (6, 'Mock Long Stopprofit'), (7, 'Mock Short Stoploss'), (8, 'Mock Long Stoploss'), (9, 'Short Fixed'), (10, 'Long Fixed'), (11, 'Mock Short Fixed'), (12, 'Mock Long Fixed'), (13, "Don't Trade")], default=1),
        ),
    ]
